// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMT1_jeICBmGCkVBbwidRUMJ9p6lrQNUw',
    appId: '1:734317095818:web:e096df9cb99ff79bcb7673',
    messagingSenderId: '734317095818',
    projectId: 'movies-db-udg',
    authDomain: 'movies-db-udg.firebaseapp.com',
    storageBucket: 'movies-db-udg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqMU-QuJHDCN-uTprxLfFL7KGjLCERAus',
    appId: '1:734317095818:android:fd34c18f1a0bf669cb7673',
    messagingSenderId: '734317095818',
    projectId: 'movies-db-udg',
    storageBucket: 'movies-db-udg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaxELeJRb5vBTKe_R-ojrE1fsEtAPfecM',
    appId: '1:734317095818:ios:5687c84521bd79facb7673',
    messagingSenderId: '734317095818',
    projectId: 'movies-db-udg',
    storageBucket: 'movies-db-udg.appspot.com',
    iosClientId:
        '734317095818-j06popsu9lrgckdc90giibi16ngi0l1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaxELeJRb5vBTKe_R-ojrE1fsEtAPfecM',
    appId: '1:734317095818:ios:5687c84521bd79facb7673',
    messagingSenderId: '734317095818',
    projectId: 'movies-db-udg',
    storageBucket: 'movies-db-udg.appspot.com',
    iosClientId:
        '734317095818-j06popsu9lrgckdc90giibi16ngi0l1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies',
  );
}
